programm
    : statement+
    ;

statement
    : identifier operator identifier operator capability "," capability
    ;

identifier
    : [a-zA-Z]+
    ;

uni_link
    : "->"
    ;

bi_link
    : "<->"
    ;

assign_property
    : "=>"
    ;

capability
    : 'position'
    ;

LineComment
    :   '#' ~[\r\n]*
        -> skip
    ;