

#ifndef SI_SIGRUN_SITypes
#define SI_SIGRUN_SITypes

#define SI_TYPE_CANVAS 0
#define SI_TYPE_CURSOR 1
#define SI_TYPE_MOUSE_CURSOR 2
#define SI_TYPE_DIRECTORY 3
#define SI_TYPE_TEXT_FILE 4
#define SI_TYPE_IMAGE_FILE 5
#define SI_TYPE_CUSTOM 9999



#define SI_DATA_TYPE_INT 0
#define SI_DATA_TYPE_FLOAT 1
#define SI_DATA_TYPE_STRING 2


#endif // SI_SIGRUN_SITypes