

#ifndef SI_SIGRUN_SITypes
#define SI_SIGRUN_SITypes

#define SI_TYPE_CANVAS 0
#define SI_TYPE_DELETION 1
#define SI_TYPE_BUTTON 2
#define SI_TYPE_NOTIFICATION 3
#define SI_TYPE_DIRECTORY 8000
#define SI_TYPE_TEXT_FILE 8001
#define SI_TYPE_IMAGE_FILE 8002
#define SI_TYPE_UNKNOWN_FILE 8003
#define SI_TYPE_CURSOR 9995
#define SI_TYPE_MOUSE_CURSOR 9998
#define SI_TYPE_CUSTOM 9999





#define SI_DATA_TYPE_INT 0
#define SI_DATA_TYPE_FLOAT 1
#define SI_DATA_TYPE_STRING 2
#define SI_DATA_TYPE_BOOL 3


#endif // SI_SIGRUN_SITypes